"""Carry local code to the Colab runtime without git.

The Colab kernel runs on a machine that cannot see this disk. Only notebook
cells travel there, so this module packs the project's code into a single cell
as a base64 zip. Running that cell unpacks the code and puts it on the import
path. Nothing is cloned and nothing is fetched.

Local use, after editing code and before running a notebook:

    python -m owlcaribou.sync            # refresh the sync cell in every notebook
    python -m owlcaribou.sync --check    # exit 1 if a notebook carries stale code or has no sync cell
    python -m owlcaribou.sync --clear    # empty the sync cells again

``--check`` reports an emptied cell as ``empty`` and does not fail on it: an
empty cell stops the notebook with a message, so it cannot run old code.

Notebooks are committed with empty sync cells so the code lives in ``src/`` and
``third_party/`` once, not as a copy inside every notebook. A notebook with an
empty sync cell stops at that cell and says what to run.

``third_party/`` travels too. That is the point of vendoring it: the runtime
never reaches out to a third party for model code.

The zip is deterministic, so identical code always gives an identical hash.
The hash is printed here and again on the runtime; if they differ, the runtime
is running old code.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import io
import json
import sys
import zipfile
from pathlib import Path

MARKER = "# === CODE SYNC (auto-generated by `python -m owlcaribou.sync`, do not edit) ==="
RUNTIME_DIR = "/content/owl-caribou-overhead"

INCLUDE_DIRS = ("src", "third_party")
INCLUDE_FILES = ("pyproject.toml",)
SKIP_DIR_NAMES = {"__pycache__", ".pytest_cache", ".ipynb_checkpoints", "results"}
SKIP_SUFFIXES = {".pyc", ".pyd", ".so", ".o", ".pt", ".pth", ".zip", ".png"}

EMPTY_SYNC_CELL = MARKER + "\n" + (
    'raise RuntimeError("The sync cell is empty. On your own machine, in the project '
    'folder, run:  python -m owlcaribou.sync   and reopen this notebook.")'
)


def collect_files(project_root: str | Path) -> list[Path]:
    """Files to ship, as sorted paths relative to the project root."""
    root = Path(project_root)
    found: list[Path] = []
    for name in INCLUDE_FILES:
        if (root / name).is_file():
            found.append(Path(name))
    for directory in INCLUDE_DIRS:
        for path in sorted((root / directory).rglob("*")):
            if not path.is_file():
                continue
            relative = path.relative_to(root)
            if any(
                part in SKIP_DIR_NAMES or part.endswith(".egg-info")
                for part in relative.parts
            ):
                continue
            if path.suffix in SKIP_SUFFIXES or path.name.startswith(".env"):
                continue
            found.append(relative)
    return sorted(found, key=lambda p: p.as_posix())


def build_payload(project_root: str | Path) -> tuple[str, str, int]:
    """Return (base64 zip, short digest, file count).

    Timestamps are fixed and line endings normalised so the same code gives
    the same hash whether packed on Windows or Linux.
    """
    root = Path(project_root)
    files = collect_files(root)
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for relative in files:
            info = zipfile.ZipInfo(relative.as_posix(), date_time=(2020, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, (root / relative).read_bytes().replace(b"\r\n", b"\n"))
    raw = buffer.getvalue()
    return base64.b64encode(raw).decode("ascii"), hashlib.sha256(raw).hexdigest()[:12], len(files)


def render_sync_cell(payload: str, digest: str, count: int) -> str:
    wrapped = "\n".join(payload[i : i + 100] for i in range(0, len(payload), 100))
    return f'''{MARKER}
# code hash: {digest} | files: {count}
import base64, io, os, shutil, sys, zipfile
from pathlib import Path

PROJECT_DIR = Path("{RUNTIME_DIR}")
PAYLOAD = """
{wrapped}
"""
for stale in {list(INCLUDE_DIRS)!r}:
    shutil.rmtree(PROJECT_DIR / stale, ignore_errors=True)
PROJECT_DIR.mkdir(parents=True, exist_ok=True)
zipfile.ZipFile(io.BytesIO(base64.b64decode(PAYLOAD))).extractall(PROJECT_DIR)
for entry in (PROJECT_DIR / "src", PROJECT_DIR / "third_party"):
    if str(entry) not in sys.path:
        sys.path.insert(0, str(entry))
for name in [m for m in sys.modules if m.split(".")[0] in ("owlcaribou", "animaloc", "dinov3")]:
    del sys.modules[name]  # a re-run picks up new code without restarting the kernel
os.environ["OWLCARIBOU_CODE_HASH"] = "{digest}"
print("code hash {digest} | {count} files unpacked to", PROJECT_DIR)'''


def _cell_text(cell: dict) -> str:
    source = cell.get("source", "")
    return "".join(source) if isinstance(source, list) else source


def update_notebook(notebook_path: str | Path, cell_source: str, write: bool = True) -> str:
    """Replace the sync cell.

    Returns 'current' if it already holds ``cell_source``, 'empty' if it is
    an emptied cell (reported only when not writing), 'updated' otherwise,
    or 'no-sync-cell'. The file is written as UTF-8 without escaping, as
    editors write notebooks, so a sync leaves unrelated cells untouched.
    """
    path = Path(notebook_path)
    notebook = json.loads(path.read_text(encoding="utf-8"))
    for cell in notebook["cells"]:
        if cell["cell_type"] == "code" and _cell_text(cell).startswith(MARKER):
            if _cell_text(cell) == cell_source:
                return "current"
            if not write and _cell_text(cell) == EMPTY_SYNC_CELL:
                return "empty"
            if write:
                cell["source"] = cell_source.splitlines(keepends=True)
                cell["outputs"] = []
                cell["execution_count"] = None
                text = json.dumps(notebook, indent=1, ensure_ascii=False) + "\n"
                try:
                    text.encode("utf-8")   # checked before the file is opened
                except UnicodeEncodeError:
                    text = json.dumps(notebook, indent=1) + "\n"
                path.write_text(text, encoding="utf-8")
            return "updated"
    return "no-sync-cell"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Pack local code into the notebooks' sync cell.")
    parser.add_argument("--root", default=".", help="project root, default: current directory")
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if a notebook is stale or has no sync cell")
    parser.add_argument("--clear", action="store_true", help="empty every sync cell")
    args = parser.parse_args(argv)
    if args.check and args.clear:
        parser.error("--check and --clear exclude each other")

    root = Path(args.root).resolve()
    if not (root / "pyproject.toml").is_file():
        print(f"{root} does not look like the project root (no pyproject.toml)")
        return 2

    if args.clear:
        cell_source = EMPTY_SYNC_CELL
        print("emptying the sync cells")
    else:
        payload, digest, count = build_payload(root)
        cell_source = render_sync_cell(payload, digest, count)
        print(f"code hash {digest} | {count} files | {len(payload) / 1024:.0f} KB in the cell")

    failed = False
    notebooks = sorted(
        path for path in (root / "notebooks").rglob("*.ipynb")
        if ".ipynb_checkpoints" not in path.parts
    )
    if not notebooks:
        print("no notebooks found")
    for notebook in notebooks:
        status = update_notebook(notebook, cell_source, write=not args.check)
        if status == "updated":
            if args.check:
                failed = True
                status = "STALE"
            else:
                status = "emptied" if args.clear else "updated"
        elif status == "no-sync-cell" and args.check:
            failed = True
            status = "NO SYNC CELL"
        print(f"  {notebook.relative_to(root / 'notebooks').as_posix()}: {status}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
